feat/680-switch-to-new-Vega-font
vegaprotocol/token-frontend pull request #1035
Opened 2021-12-03 11:08 UTC by pgriscti

closes #680

2021-12-03 11:15 UTC, campbellssource requested changes
As well as importing the new font this PR should remove the pixelate every x chartacter behaviour used in the page titles and replace ensure the new font is used for the whole title.
The new font has the "random" pixelation built in.

2021-12-03 19:24 UTC, mattrussell36 approved these changes

2021-12-03 19:25 UTC, mattrussell36 requested changes
As state by Michael need to remove the pixel randomisation in the heading component

2021-12-06 10:57 UTC, pgriscti commented
> As well as importing the new font this PR should remove the pixelate every x chartacter behaviour used in the page titles and ensure the new font is used for the whole title. The new font has the "random" pixelation built in.
> 
> Sorry this wasn't mentioned in the ticket

done

2021-12-06 12:29 UTC, dexturr approved these changes

2021-12-06 18:25 UTC, mattrussell36 approved these changes

2021-12-06 18:25 UTC, merged