remove version in wallet
vegaprotocol/token-frontend pull request #1198
Opened 2022-03-02 14:46 UTC by dexturr

2022-03-07 10:34 UTC, edd approved these changes

2022-03-07 11:31 UTC, dexturr commented
Thanks @edd, realized this actually needed a lot more 🙈 

@mattrussell36 would be good to get your eyes on this one as well as I haven't done much in the wallet place

2022-03-08 01:05 UTC, mattrussell36 requested changes
Couple fixes required here.

2022-03-08 01:05 UTC, mattrussell36 commented on src/components/vega-wallet/vega-wallet-container.tsx
> +      console.log(version);
Stray console.log here and variable name should change

```suggestion
      const [err] = await vegWalletService.getKeys();
```

2022-03-08 01:05 UTC, mattrussell36 commented on src/lib/vega-wallet/vega-wallet-service.ts
> -import semver from "semver";
I think this is the only place we use this package so it can be removed from package.json

2022-03-08 13:23 UTC, merged